source 'https://rubygems.org'
gem 'rails', '4.2.2'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'therubyracer', platforms: :ruby
gem 'haml-rails'
gem 'bcrypt', '~> 3.1.7'
gem 'unicorn'
gem 'bootstrap-sass'
gem 'fontawesome-rails'
gem 'twitter_bootstrap_form_for', github: 'tamouse/twitter_bootstrap_form_for'

# Added for exploration
gem 'devise'
gem 'cancan'

group :development, :test do
  gem 'capistrano-rails'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'awesome_print'
  gem 'rspec-rails'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets'
  gem 'html2haml'
  gem 'mailcatcher'
end
